services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/task_manager?schema=public
      JWT_SECRET: dev-secret
      JWT_EXPIRES_IN: 1d
      PORT: 3000
      NODE_ENV: development
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy && node dist/server.js"
volumes:
  pgdata:
